name: C/C++ CI

env:
  lab: 'lab-0'

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  checking:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check testing file
      run: |
        if [ ! -f "${{ env.lab }}/testing/makefile" ]; then
          echo "Testing file not found"
          exit 1
        fi

  testing:
    needs: checking
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Cpp
      uses: aminya/setup-cpp@v0.37.0
      with:
        compiler: gcc
      
    - name: Test make
      run: |
        cd ${{ env.lab }}/testing
        pwd
        make run
